version: 2
before:
  hooks:
    - go mod tidy

env:
  - DOCKER_IMAGE_REPO={{ envOrDefault "DOCKER_IMAGE_REPO" "builder" }}

builds:
  - id: knox
    binary: knox
    main: main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/zeiss/knox/cmd.version={{.Version}} -X github.com/zeiss/knox/cmd.commit={{.Commit}} -X github.com/zeiss/knox/cmd.date={{.Date}}

dockers_v2:
  - id: knox
    dockerfile: Dockerfile
    images:
      - "{{ .Env.DOCKER_IMAGE_REPO }}/knox"
    tags:
      - "{{ .Version }}"
      - latest
    ids:
      - knox
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"

archives:
  - id: knox
    builds:
      - knox
    name_template: "knox_{{.Version}}_{{.Os}}_{{.Arch}}"

release:
  draft: false
  name_template: "v{{ .Version }}"
  header: |
    ## {{.Version}} Release ({{ .Date }})

    Welcome to this new release :rocket:!
  footer: |
    ## Thanks!

    Those were the changes on {{ .Tag }}!

changelog:
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - typo
      - (?i)foo

checksum:
  name_template: "knox_checksums.txt"
