// Package apis provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apis

import (
	"context"
	"fmt"
	"net/url"

	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get system health status
	// (GET /_health)
	GetHealth(c *fiber.Ctx) error
	// Get system readiness
	// (GET /_ready)
	GetReady(c *fiber.Ctx) error
	// Lock the state of Terraform environment
	// (POST /client/{teamName}/{projectName}/{environmentName}/lock)
	LockEnvironment(c *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName) error
	// Get the state of Terraform environment
	// (GET /client/{teamName}/{projectName}/{environmentName}/state)
	GetEnvironmentState(c *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName) error
	// Update the state of Terraform environment
	// (POST /client/{teamName}/{projectName}/{environmentName}/state)
	UpdateEnvironmentState(c *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName) error
	// Unlock the state of Terraform environment
	// (POST /client/{teamName}/{projectName}/{environmentName}/unlock)
	UnlockEnvironment(c *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName) error
	// Get a list of teams
	// (GET /teams)
	GetTeams(c *fiber.Ctx, params GetTeamsParams) error
	// Create a new team
	// (POST /teams)
	CreateTeam(c *fiber.Ctx) error
	// Delete a team
	// (DELETE /teams/{teamName})
	DeleteTeam(c *fiber.Ctx, teamName TeamName) error
	// Get a team
	// (GET /teams/{teamName})
	GetTeam(c *fiber.Ctx, teamName TeamName) error
	// Update a team
	// (PUT /teams/{teamName})
	UpdateTeam(c *fiber.Ctx, teamName TeamName) error
	// Get a list of projects
	// (GET /teams/{teamName}/projects)
	GetProjects(c *fiber.Ctx, teamName TeamName, params GetProjectsParams) error
	// Create a new project
	// (POST /teams/{teamName}/projects)
	CreateProject(c *fiber.Ctx, teamName TeamName) error
	// Delete a project
	// (DELETE /teams/{teamName}/projects/{projectName})
	DeleteProject(c *fiber.Ctx, teamName TeamName, projectName ProjectName) error
	// Get a project
	// (GET /teams/{teamName}/projects/{projectName})
	GetProject(c *fiber.Ctx, teamName TeamName, projectName ProjectName) error
	// Update a project
	// (PUT /teams/{teamName}/projects/{projectName})
	UpdateProject(c *fiber.Ctx, teamName TeamName, projectName ProjectName) error
	// Get a list of environments
	// (GET /teams/{teamName}/projects/{projectName}/environments)
	GetEnvironments(c *fiber.Ctx, teamName TeamName, projectName ProjectName, params GetEnvironmentsParams) error
	// Create a new environment
	// (POST /teams/{teamName}/projects/{projectName}/environments)
	CreateEnvironment(c *fiber.Ctx, teamName TeamName, projectName ProjectName) error
	// Delete an environment
	// (DELETE /teams/{teamName}/projects/{projectName}/environments/{environmentName})
	DeleteEnvironment(c *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName) error
	// Get an environment
	// (GET /teams/{teamName}/projects/{projectName}/environments/{environmentName})
	GetEnvironment(c *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName) error
	// Update an environment
	// (PUT /teams/{teamName}/projects/{projectName}/environments/{environmentName})
	UpdateEnvironment(c *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName) error
	// Get a list of snapshots
	// (GET /teams/{teamName}/projects/{projectName}/environments/{environmentName}/snapshots)
	GetSnapshots(c *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName, params GetSnapshotsParams) error
	// Create a new snapshot
	// (POST /teams/{teamName}/projects/{projectName}/environments/{environmentName}/snapshots)
	CreateSnapshot(c *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName) error
	// Delete a snapshot
	// (DELETE /teams/{teamName}/projects/{projectName}/environments/{environmentName}/snapshots/{snapshotId})
	DeleteSnapshot(c *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName, snapshotId SnapshotId) error
	// Get a snapshot
	// (GET /teams/{teamName}/projects/{projectName}/environments/{environmentName}/snapshots/{snapshotId})
	GetSnapshot(c *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName, snapshotId SnapshotId) error
	// Get the state of Terraform environment
	// (GET /teams/{teamName}/projects/{projectName}/environments/{environmentName}/states)
	GetStates(c *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName, params GetStatesParams) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *fiber.Ctx) error {

	return siw.Handler.GetHealth(c)
}

// GetReady operation middleware
func (siw *ServerInterfaceWrapper) GetReady(c *fiber.Ctx) error {

	return siw.Handler.GetReady(c)
}

// LockEnvironment operation middleware
func (siw *ServerInterfaceWrapper) LockEnvironment(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	// ------------- Path parameter "environmentName" -------------
	var environmentName EnvironmentName

	err = runtime.BindStyledParameterWithOptions("simple", "environmentName", c.Params("environmentName"), &environmentName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentName: %w", err).Error())
	}

	c.Context().SetUserValue(BasicAuthScopes, []string{})

	return siw.Handler.LockEnvironment(c, teamName, projectName, environmentName)
}

// GetEnvironmentState operation middleware
func (siw *ServerInterfaceWrapper) GetEnvironmentState(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	// ------------- Path parameter "environmentName" -------------
	var environmentName EnvironmentName

	err = runtime.BindStyledParameterWithOptions("simple", "environmentName", c.Params("environmentName"), &environmentName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentName: %w", err).Error())
	}

	c.Context().SetUserValue(BasicAuthScopes, []string{})

	return siw.Handler.GetEnvironmentState(c, teamName, projectName, environmentName)
}

// UpdateEnvironmentState operation middleware
func (siw *ServerInterfaceWrapper) UpdateEnvironmentState(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	// ------------- Path parameter "environmentName" -------------
	var environmentName EnvironmentName

	err = runtime.BindStyledParameterWithOptions("simple", "environmentName", c.Params("environmentName"), &environmentName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentName: %w", err).Error())
	}

	c.Context().SetUserValue(BasicAuthScopes, []string{})

	return siw.Handler.UpdateEnvironmentState(c, teamName, projectName, environmentName)
}

// UnlockEnvironment operation middleware
func (siw *ServerInterfaceWrapper) UnlockEnvironment(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	// ------------- Path parameter "environmentName" -------------
	var environmentName EnvironmentName

	err = runtime.BindStyledParameterWithOptions("simple", "environmentName", c.Params("environmentName"), &environmentName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentName: %w", err).Error())
	}

	c.Context().SetUserValue(BasicAuthScopes, []string{})

	return siw.Handler.UnlockEnvironment(c, teamName, projectName, environmentName)
}

// GetTeams operation middleware
func (siw *ServerInterfaceWrapper) GetTeams(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(OpenIdScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetTeams(c, params)
}

// CreateTeam operation middleware
func (siw *ServerInterfaceWrapper) CreateTeam(c *fiber.Ctx) error {

	c.Context().SetUserValue(OpenIdScopes, []string{})

	return siw.Handler.CreateTeam(c)
}

// DeleteTeam operation middleware
func (siw *ServerInterfaceWrapper) DeleteTeam(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	return siw.Handler.DeleteTeam(c, teamName)
}

// GetTeam operation middleware
func (siw *ServerInterfaceWrapper) GetTeam(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	return siw.Handler.GetTeam(c, teamName)
}

// UpdateTeam operation middleware
func (siw *ServerInterfaceWrapper) UpdateTeam(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	return siw.Handler.UpdateTeam(c, teamName)
}

// GetProjects operation middleware
func (siw *ServerInterfaceWrapper) GetProjects(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProjectsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetProjects(c, teamName, params)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	return siw.Handler.CreateProject(c, teamName)
}

// DeleteProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteProject(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	return siw.Handler.DeleteProject(c, teamName, projectName)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	return siw.Handler.GetProject(c, teamName, projectName)
}

// UpdateProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateProject(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	return siw.Handler.UpdateProject(c, teamName, projectName)
}

// GetEnvironments operation middleware
func (siw *ServerInterfaceWrapper) GetEnvironments(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEnvironmentsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetEnvironments(c, teamName, projectName, params)
}

// CreateEnvironment operation middleware
func (siw *ServerInterfaceWrapper) CreateEnvironment(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	return siw.Handler.CreateEnvironment(c, teamName, projectName)
}

// DeleteEnvironment operation middleware
func (siw *ServerInterfaceWrapper) DeleteEnvironment(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	// ------------- Path parameter "environmentName" -------------
	var environmentName EnvironmentName

	err = runtime.BindStyledParameterWithOptions("simple", "environmentName", c.Params("environmentName"), &environmentName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentName: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	return siw.Handler.DeleteEnvironment(c, teamName, projectName, environmentName)
}

// GetEnvironment operation middleware
func (siw *ServerInterfaceWrapper) GetEnvironment(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	// ------------- Path parameter "environmentName" -------------
	var environmentName EnvironmentName

	err = runtime.BindStyledParameterWithOptions("simple", "environmentName", c.Params("environmentName"), &environmentName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentName: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	return siw.Handler.GetEnvironment(c, teamName, projectName, environmentName)
}

// UpdateEnvironment operation middleware
func (siw *ServerInterfaceWrapper) UpdateEnvironment(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	// ------------- Path parameter "environmentName" -------------
	var environmentName EnvironmentName

	err = runtime.BindStyledParameterWithOptions("simple", "environmentName", c.Params("environmentName"), &environmentName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentName: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	return siw.Handler.UpdateEnvironment(c, teamName, projectName, environmentName)
}

// GetSnapshots operation middleware
func (siw *ServerInterfaceWrapper) GetSnapshots(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	// ------------- Path parameter "environmentName" -------------
	var environmentName EnvironmentName

	err = runtime.BindStyledParameterWithOptions("simple", "environmentName", c.Params("environmentName"), &environmentName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentName: %w", err).Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSnapshotsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetSnapshots(c, teamName, projectName, environmentName, params)
}

// CreateSnapshot operation middleware
func (siw *ServerInterfaceWrapper) CreateSnapshot(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	// ------------- Path parameter "environmentName" -------------
	var environmentName EnvironmentName

	err = runtime.BindStyledParameterWithOptions("simple", "environmentName", c.Params("environmentName"), &environmentName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentName: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	return siw.Handler.CreateSnapshot(c, teamName, projectName, environmentName)
}

// DeleteSnapshot operation middleware
func (siw *ServerInterfaceWrapper) DeleteSnapshot(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	// ------------- Path parameter "environmentName" -------------
	var environmentName EnvironmentName

	err = runtime.BindStyledParameterWithOptions("simple", "environmentName", c.Params("environmentName"), &environmentName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentName: %w", err).Error())
	}

	// ------------- Path parameter "snapshotId" -------------
	var snapshotId SnapshotId

	err = runtime.BindStyledParameterWithOptions("simple", "snapshotId", c.Params("snapshotId"), &snapshotId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter snapshotId: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	return siw.Handler.DeleteSnapshot(c, teamName, projectName, environmentName, snapshotId)
}

// GetSnapshot operation middleware
func (siw *ServerInterfaceWrapper) GetSnapshot(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	// ------------- Path parameter "environmentName" -------------
	var environmentName EnvironmentName

	err = runtime.BindStyledParameterWithOptions("simple", "environmentName", c.Params("environmentName"), &environmentName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentName: %w", err).Error())
	}

	// ------------- Path parameter "snapshotId" -------------
	var snapshotId SnapshotId

	err = runtime.BindStyledParameterWithOptions("simple", "snapshotId", c.Params("snapshotId"), &snapshotId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter snapshotId: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	return siw.Handler.GetSnapshot(c, teamName, projectName, environmentName, snapshotId)
}

// GetStates operation middleware
func (siw *ServerInterfaceWrapper) GetStates(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamName" -------------
	var teamName TeamName

	err = runtime.BindStyledParameterWithOptions("simple", "teamName", c.Params("teamName"), &teamName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamName: %w", err).Error())
	}

	// ------------- Path parameter "projectName" -------------
	var projectName ProjectName

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Params("projectName"), &projectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectName: %w", err).Error())
	}

	// ------------- Path parameter "environmentName" -------------
	var environmentName EnvironmentName

	err = runtime.BindStyledParameterWithOptions("simple", "environmentName", c.Params("environmentName"), &environmentName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentName: %w", err).Error())
	}

	c.Context().SetUserValue(OpenIdScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStatesParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetStates(c, teamName, projectName, environmentName, params)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/_health", wrapper.GetHealth)

	router.Get(options.BaseURL+"/_ready", wrapper.GetReady)

	router.Post(options.BaseURL+"/client/:teamName/:projectName/:environmentName/lock", wrapper.LockEnvironment)

	router.Get(options.BaseURL+"/client/:teamName/:projectName/:environmentName/state", wrapper.GetEnvironmentState)

	router.Post(options.BaseURL+"/client/:teamName/:projectName/:environmentName/state", wrapper.UpdateEnvironmentState)

	router.Post(options.BaseURL+"/client/:teamName/:projectName/:environmentName/unlock", wrapper.UnlockEnvironment)

	router.Get(options.BaseURL+"/teams", wrapper.GetTeams)

	router.Post(options.BaseURL+"/teams", wrapper.CreateTeam)

	router.Delete(options.BaseURL+"/teams/:teamName", wrapper.DeleteTeam)

	router.Get(options.BaseURL+"/teams/:teamName", wrapper.GetTeam)

	router.Put(options.BaseURL+"/teams/:teamName", wrapper.UpdateTeam)

	router.Get(options.BaseURL+"/teams/:teamName/projects", wrapper.GetProjects)

	router.Post(options.BaseURL+"/teams/:teamName/projects", wrapper.CreateProject)

	router.Delete(options.BaseURL+"/teams/:teamName/projects/:projectName", wrapper.DeleteProject)

	router.Get(options.BaseURL+"/teams/:teamName/projects/:projectName", wrapper.GetProject)

	router.Put(options.BaseURL+"/teams/:teamName/projects/:projectName", wrapper.UpdateProject)

	router.Get(options.BaseURL+"/teams/:teamName/projects/:projectName/environments", wrapper.GetEnvironments)

	router.Post(options.BaseURL+"/teams/:teamName/projects/:projectName/environments", wrapper.CreateEnvironment)

	router.Delete(options.BaseURL+"/teams/:teamName/projects/:projectName/environments/:environmentName", wrapper.DeleteEnvironment)

	router.Get(options.BaseURL+"/teams/:teamName/projects/:projectName/environments/:environmentName", wrapper.GetEnvironment)

	router.Put(options.BaseURL+"/teams/:teamName/projects/:projectName/environments/:environmentName", wrapper.UpdateEnvironment)

	router.Get(options.BaseURL+"/teams/:teamName/projects/:projectName/environments/:environmentName/snapshots", wrapper.GetSnapshots)

	router.Post(options.BaseURL+"/teams/:teamName/projects/:projectName/environments/:environmentName/snapshots", wrapper.CreateSnapshot)

	router.Delete(options.BaseURL+"/teams/:teamName/projects/:projectName/environments/:environmentName/snapshots/:snapshotId", wrapper.DeleteSnapshot)

	router.Get(options.BaseURL+"/teams/:teamName/projects/:projectName/environments/:environmentName/snapshots/:snapshotId", wrapper.GetSnapshot)

	router.Get(options.BaseURL+"/teams/:teamName/projects/:projectName/environments/:environmentName/states", wrapper.GetStates)

}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(ctx *fiber.Ctx) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetHealth500JSONResponse HealthResponse

func (response GetHealth500JSONResponse) VisitGetHealthResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetReadyRequestObject struct {
}

type GetReadyResponseObject interface {
	VisitGetReadyResponse(ctx *fiber.Ctx) error
}

type GetReady200JSONResponse HealthResponse

func (response GetReady200JSONResponse) VisitGetReadyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetReady500JSONResponse HealthResponse

func (response GetReady500JSONResponse) VisitGetReadyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type LockEnvironmentRequestObject struct {
	TeamName        TeamName        `json:"teamName"`
	ProjectName     ProjectName     `json:"projectName"`
	EnvironmentName EnvironmentName `json:"environmentName"`
	Body            *LockEnvironmentJSONRequestBody
}

type LockEnvironmentResponseObject interface {
	VisitLockEnvironmentResponse(ctx *fiber.Ctx) error
}

type LockEnvironment200JSONResponse LockInfo

func (response LockEnvironment200JSONResponse) VisitLockEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type LockEnvironment404JSONResponse ErrorResponse

func (response LockEnvironment404JSONResponse) VisitLockEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type LockEnvironment500JSONResponse ErrorResponse

func (response LockEnvironment500JSONResponse) VisitLockEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetEnvironmentStateRequestObject struct {
	TeamName        TeamName        `json:"teamName"`
	ProjectName     ProjectName     `json:"projectName"`
	EnvironmentName EnvironmentName `json:"environmentName"`
}

type GetEnvironmentStateResponseObject interface {
	VisitGetEnvironmentStateResponse(ctx *fiber.Ctx) error
}

type GetEnvironmentState200JSONResponse Payload

func (response GetEnvironmentState200JSONResponse) VisitGetEnvironmentStateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetEnvironmentState404JSONResponse ErrorResponse

func (response GetEnvironmentState404JSONResponse) VisitGetEnvironmentStateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetEnvironmentState500JSONResponse ErrorResponse

func (response GetEnvironmentState500JSONResponse) VisitGetEnvironmentStateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type UpdateEnvironmentStateRequestObject struct {
	TeamName        TeamName        `json:"teamName"`
	ProjectName     ProjectName     `json:"projectName"`
	EnvironmentName EnvironmentName `json:"environmentName"`
	Body            *UpdateEnvironmentStateJSONRequestBody
}

type UpdateEnvironmentStateResponseObject interface {
	VisitUpdateEnvironmentStateResponse(ctx *fiber.Ctx) error
}

type UpdateEnvironmentState200JSONResponse Payload

func (response UpdateEnvironmentState200JSONResponse) VisitUpdateEnvironmentStateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type UpdateEnvironmentState404JSONResponse ErrorResponse

func (response UpdateEnvironmentState404JSONResponse) VisitUpdateEnvironmentStateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type UpdateEnvironmentState500JSONResponse ErrorResponse

func (response UpdateEnvironmentState500JSONResponse) VisitUpdateEnvironmentStateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type UnlockEnvironmentRequestObject struct {
	TeamName        TeamName        `json:"teamName"`
	ProjectName     ProjectName     `json:"projectName"`
	EnvironmentName EnvironmentName `json:"environmentName"`
	Body            *UnlockEnvironmentJSONRequestBody
}

type UnlockEnvironmentResponseObject interface {
	VisitUnlockEnvironmentResponse(ctx *fiber.Ctx) error
}

type UnlockEnvironment200Response struct {
}

func (response UnlockEnvironment200Response) VisitUnlockEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type UnlockEnvironment204Response struct {
}

func (response UnlockEnvironment204Response) VisitUnlockEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type UnlockEnvironment404JSONResponse ErrorResponse

func (response UnlockEnvironment404JSONResponse) VisitUnlockEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type UnlockEnvironment500JSONResponse ErrorResponse

func (response UnlockEnvironment500JSONResponse) VisitUnlockEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetTeamsRequestObject struct {
	Params GetTeamsParams
}

type GetTeamsResponseObject interface {
	VisitGetTeamsResponse(ctx *fiber.Ctx) error
}

type GetTeams200JSONResponse struct {
	Metadata *struct {
		Limit      *int `json:"limit,omitempty"`
		Offset     *int `json:"offset,omitempty"`
		TotalCount *int `json:"totalCount,omitempty"`
	} `json:"metadata,omitempty"`
	Teams *[]Team `json:"teams,omitempty"`
}

func (response GetTeams200JSONResponse) VisitGetTeamsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetTeams500JSONResponse ErrorResponse

func (response GetTeams500JSONResponse) VisitGetTeamsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type CreateTeamRequestObject struct {
	Body *CreateTeamJSONRequestBody
}

type CreateTeamResponseObject interface {
	VisitCreateTeamResponse(ctx *fiber.Ctx) error
}

type CreateTeam201JSONResponse Team

func (response CreateTeam201JSONResponse) VisitCreateTeamResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type CreateTeam500JSONResponse ErrorResponse

func (response CreateTeam500JSONResponse) VisitCreateTeamResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type DeleteTeamRequestObject struct {
	TeamName TeamName `json:"teamName"`
}

type DeleteTeamResponseObject interface {
	VisitDeleteTeamResponse(ctx *fiber.Ctx) error
}

type DeleteTeam204Response struct {
}

func (response DeleteTeam204Response) VisitDeleteTeamResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type DeleteTeam404JSONResponse ErrorResponse

func (response DeleteTeam404JSONResponse) VisitDeleteTeamResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type DeleteTeam500JSONResponse ErrorResponse

func (response DeleteTeam500JSONResponse) VisitDeleteTeamResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetTeamRequestObject struct {
	TeamName TeamName `json:"teamName"`
}

type GetTeamResponseObject interface {
	VisitGetTeamResponse(ctx *fiber.Ctx) error
}

type GetTeam200JSONResponse Team

func (response GetTeam200JSONResponse) VisitGetTeamResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetTeam404JSONResponse ErrorResponse

func (response GetTeam404JSONResponse) VisitGetTeamResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetTeam500JSONResponse ErrorResponse

func (response GetTeam500JSONResponse) VisitGetTeamResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type UpdateTeamRequestObject struct {
	TeamName TeamName `json:"teamName"`
	Body     *UpdateTeamJSONRequestBody
}

type UpdateTeamResponseObject interface {
	VisitUpdateTeamResponse(ctx *fiber.Ctx) error
}

type UpdateTeam200JSONResponse Team

func (response UpdateTeam200JSONResponse) VisitUpdateTeamResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type UpdateTeam404JSONResponse ErrorResponse

func (response UpdateTeam404JSONResponse) VisitUpdateTeamResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type UpdateTeam500JSONResponse ErrorResponse

func (response UpdateTeam500JSONResponse) VisitUpdateTeamResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetProjectsRequestObject struct {
	TeamName TeamName `json:"teamName"`
	Params   GetProjectsParams
}

type GetProjectsResponseObject interface {
	VisitGetProjectsResponse(ctx *fiber.Ctx) error
}

type GetProjects200JSONResponse struct {
	Metadata *struct {
		Limit      *int `json:"limit,omitempty"`
		Offset     *int `json:"offset,omitempty"`
		TotalCount *int `json:"totalCount,omitempty"`
	} `json:"metadata,omitempty"`
	Projects *[]Project `json:"projects,omitempty"`
}

func (response GetProjects200JSONResponse) VisitGetProjectsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetProjects500JSONResponse ErrorResponse

func (response GetProjects500JSONResponse) VisitGetProjectsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type CreateProjectRequestObject struct {
	TeamName TeamName `json:"teamName"`
	Body     *CreateProjectJSONRequestBody
}

type CreateProjectResponseObject interface {
	VisitCreateProjectResponse(ctx *fiber.Ctx) error
}

type CreateProject201JSONResponse Project

func (response CreateProject201JSONResponse) VisitCreateProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type CreateProject500JSONResponse ErrorResponse

func (response CreateProject500JSONResponse) VisitCreateProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type DeleteProjectRequestObject struct {
	TeamName    TeamName    `json:"teamName"`
	ProjectName ProjectName `json:"projectName"`
}

type DeleteProjectResponseObject interface {
	VisitDeleteProjectResponse(ctx *fiber.Ctx) error
}

type DeleteProject204Response struct {
}

func (response DeleteProject204Response) VisitDeleteProjectResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type DeleteProject404JSONResponse ErrorResponse

func (response DeleteProject404JSONResponse) VisitDeleteProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type DeleteProject500JSONResponse ErrorResponse

func (response DeleteProject500JSONResponse) VisitDeleteProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetProjectRequestObject struct {
	TeamName    TeamName    `json:"teamName"`
	ProjectName ProjectName `json:"projectName"`
}

type GetProjectResponseObject interface {
	VisitGetProjectResponse(ctx *fiber.Ctx) error
}

type GetProject200JSONResponse Project

func (response GetProject200JSONResponse) VisitGetProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetProject404JSONResponse ErrorResponse

func (response GetProject404JSONResponse) VisitGetProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetProject500JSONResponse ErrorResponse

func (response GetProject500JSONResponse) VisitGetProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type UpdateProjectRequestObject struct {
	TeamName    TeamName    `json:"teamName"`
	ProjectName ProjectName `json:"projectName"`
	Body        *UpdateProjectJSONRequestBody
}

type UpdateProjectResponseObject interface {
	VisitUpdateProjectResponse(ctx *fiber.Ctx) error
}

type UpdateProject200JSONResponse Project

func (response UpdateProject200JSONResponse) VisitUpdateProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type UpdateProject404JSONResponse ErrorResponse

func (response UpdateProject404JSONResponse) VisitUpdateProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type UpdateProject500JSONResponse ErrorResponse

func (response UpdateProject500JSONResponse) VisitUpdateProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetEnvironmentsRequestObject struct {
	TeamName    TeamName    `json:"teamName"`
	ProjectName ProjectName `json:"projectName"`
	Params      GetEnvironmentsParams
}

type GetEnvironmentsResponseObject interface {
	VisitGetEnvironmentsResponse(ctx *fiber.Ctx) error
}

type GetEnvironments200JSONResponse struct {
	Environments *[]Environment `json:"environments,omitempty"`
	Metadata     *struct {
		Limit      *int `json:"limit,omitempty"`
		Offset     *int `json:"offset,omitempty"`
		TotalCount *int `json:"totalCount,omitempty"`
	} `json:"metadata,omitempty"`
}

func (response GetEnvironments200JSONResponse) VisitGetEnvironmentsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetEnvironments500JSONResponse ErrorResponse

func (response GetEnvironments500JSONResponse) VisitGetEnvironmentsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type CreateEnvironmentRequestObject struct {
	TeamName    TeamName    `json:"teamName"`
	ProjectName ProjectName `json:"projectName"`
	Body        *CreateEnvironmentJSONRequestBody
}

type CreateEnvironmentResponseObject interface {
	VisitCreateEnvironmentResponse(ctx *fiber.Ctx) error
}

type CreateEnvironment201JSONResponse Environment

func (response CreateEnvironment201JSONResponse) VisitCreateEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type CreateEnvironment500JSONResponse ErrorResponse

func (response CreateEnvironment500JSONResponse) VisitCreateEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type DeleteEnvironmentRequestObject struct {
	TeamName        TeamName        `json:"teamName"`
	ProjectName     ProjectName     `json:"projectName"`
	EnvironmentName EnvironmentName `json:"environmentName"`
}

type DeleteEnvironmentResponseObject interface {
	VisitDeleteEnvironmentResponse(ctx *fiber.Ctx) error
}

type DeleteEnvironment204Response struct {
}

func (response DeleteEnvironment204Response) VisitDeleteEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type DeleteEnvironment404JSONResponse ErrorResponse

func (response DeleteEnvironment404JSONResponse) VisitDeleteEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type DeleteEnvironment500JSONResponse ErrorResponse

func (response DeleteEnvironment500JSONResponse) VisitDeleteEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetEnvironmentRequestObject struct {
	TeamName        TeamName        `json:"teamName"`
	ProjectName     ProjectName     `json:"projectName"`
	EnvironmentName EnvironmentName `json:"environmentName"`
}

type GetEnvironmentResponseObject interface {
	VisitGetEnvironmentResponse(ctx *fiber.Ctx) error
}

type GetEnvironment200JSONResponse Environment

func (response GetEnvironment200JSONResponse) VisitGetEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetEnvironment404JSONResponse ErrorResponse

func (response GetEnvironment404JSONResponse) VisitGetEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetEnvironment500JSONResponse ErrorResponse

func (response GetEnvironment500JSONResponse) VisitGetEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type UpdateEnvironmentRequestObject struct {
	TeamName        TeamName        `json:"teamName"`
	ProjectName     ProjectName     `json:"projectName"`
	EnvironmentName EnvironmentName `json:"environmentName"`
	Body            *UpdateEnvironmentJSONRequestBody
}

type UpdateEnvironmentResponseObject interface {
	VisitUpdateEnvironmentResponse(ctx *fiber.Ctx) error
}

type UpdateEnvironment200JSONResponse Environment

func (response UpdateEnvironment200JSONResponse) VisitUpdateEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type UpdateEnvironment404JSONResponse ErrorResponse

func (response UpdateEnvironment404JSONResponse) VisitUpdateEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type UpdateEnvironment500JSONResponse ErrorResponse

func (response UpdateEnvironment500JSONResponse) VisitUpdateEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetSnapshotsRequestObject struct {
	TeamName        TeamName        `json:"teamName"`
	ProjectName     ProjectName     `json:"projectName"`
	EnvironmentName EnvironmentName `json:"environmentName"`
	Params          GetSnapshotsParams
}

type GetSnapshotsResponseObject interface {
	VisitGetSnapshotsResponse(ctx *fiber.Ctx) error
}

type GetSnapshots200JSONResponse struct {
	Metadata *struct {
		Limit      *int `json:"limit,omitempty"`
		Offset     *int `json:"offset,omitempty"`
		TotalCount *int `json:"totalCount,omitempty"`
	} `json:"metadata,omitempty"`
	Snapshots *[]Snapshot `json:"snapshots,omitempty"`
}

func (response GetSnapshots200JSONResponse) VisitGetSnapshotsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetSnapshots500JSONResponse ErrorResponse

func (response GetSnapshots500JSONResponse) VisitGetSnapshotsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type CreateSnapshotRequestObject struct {
	TeamName        TeamName        `json:"teamName"`
	ProjectName     ProjectName     `json:"projectName"`
	EnvironmentName EnvironmentName `json:"environmentName"`
	Body            *CreateSnapshotJSONRequestBody
}

type CreateSnapshotResponseObject interface {
	VisitCreateSnapshotResponse(ctx *fiber.Ctx) error
}

type CreateSnapshot201JSONResponse Snapshot

func (response CreateSnapshot201JSONResponse) VisitCreateSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type CreateSnapshot500JSONResponse ErrorResponse

func (response CreateSnapshot500JSONResponse) VisitCreateSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type DeleteSnapshotRequestObject struct {
	TeamName        TeamName        `json:"teamName"`
	ProjectName     ProjectName     `json:"projectName"`
	EnvironmentName EnvironmentName `json:"environmentName"`
	SnapshotId      SnapshotId      `json:"snapshotId"`
}

type DeleteSnapshotResponseObject interface {
	VisitDeleteSnapshotResponse(ctx *fiber.Ctx) error
}

type DeleteSnapshot204Response struct {
}

func (response DeleteSnapshot204Response) VisitDeleteSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type DeleteSnapshot404JSONResponse ErrorResponse

func (response DeleteSnapshot404JSONResponse) VisitDeleteSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type DeleteSnapshot500JSONResponse ErrorResponse

func (response DeleteSnapshot500JSONResponse) VisitDeleteSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetSnapshotRequestObject struct {
	TeamName        TeamName        `json:"teamName"`
	ProjectName     ProjectName     `json:"projectName"`
	EnvironmentName EnvironmentName `json:"environmentName"`
	SnapshotId      SnapshotId      `json:"snapshotId"`
}

type GetSnapshotResponseObject interface {
	VisitGetSnapshotResponse(ctx *fiber.Ctx) error
}

type GetSnapshot200JSONResponse Snapshot

func (response GetSnapshot200JSONResponse) VisitGetSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetSnapshot404JSONResponse ErrorResponse

func (response GetSnapshot404JSONResponse) VisitGetSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetSnapshot500JSONResponse ErrorResponse

func (response GetSnapshot500JSONResponse) VisitGetSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetStatesRequestObject struct {
	TeamName        TeamName        `json:"teamName"`
	ProjectName     ProjectName     `json:"projectName"`
	EnvironmentName EnvironmentName `json:"environmentName"`
	Params          GetStatesParams
}

type GetStatesResponseObject interface {
	VisitGetStatesResponse(ctx *fiber.Ctx) error
}

type GetStates200JSONResponse struct {
	States *[]State `json:"states,omitempty"`
}

func (response GetStates200JSONResponse) VisitGetStatesResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetStates404JSONResponse ErrorResponse

func (response GetStates404JSONResponse) VisitGetStatesResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetStates500JSONResponse ErrorResponse

func (response GetStates500JSONResponse) VisitGetStatesResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get system health status
	// (GET /_health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Get system readiness
	// (GET /_ready)
	GetReady(ctx context.Context, request GetReadyRequestObject) (GetReadyResponseObject, error)
	// Lock the state of Terraform environment
	// (POST /client/{teamName}/{projectName}/{environmentName}/lock)
	LockEnvironment(ctx context.Context, request LockEnvironmentRequestObject) (LockEnvironmentResponseObject, error)
	// Get the state of Terraform environment
	// (GET /client/{teamName}/{projectName}/{environmentName}/state)
	GetEnvironmentState(ctx context.Context, request GetEnvironmentStateRequestObject) (GetEnvironmentStateResponseObject, error)
	// Update the state of Terraform environment
	// (POST /client/{teamName}/{projectName}/{environmentName}/state)
	UpdateEnvironmentState(ctx context.Context, request UpdateEnvironmentStateRequestObject) (UpdateEnvironmentStateResponseObject, error)
	// Unlock the state of Terraform environment
	// (POST /client/{teamName}/{projectName}/{environmentName}/unlock)
	UnlockEnvironment(ctx context.Context, request UnlockEnvironmentRequestObject) (UnlockEnvironmentResponseObject, error)
	// Get a list of teams
	// (GET /teams)
	GetTeams(ctx context.Context, request GetTeamsRequestObject) (GetTeamsResponseObject, error)
	// Create a new team
	// (POST /teams)
	CreateTeam(ctx context.Context, request CreateTeamRequestObject) (CreateTeamResponseObject, error)
	// Delete a team
	// (DELETE /teams/{teamName})
	DeleteTeam(ctx context.Context, request DeleteTeamRequestObject) (DeleteTeamResponseObject, error)
	// Get a team
	// (GET /teams/{teamName})
	GetTeam(ctx context.Context, request GetTeamRequestObject) (GetTeamResponseObject, error)
	// Update a team
	// (PUT /teams/{teamName})
	UpdateTeam(ctx context.Context, request UpdateTeamRequestObject) (UpdateTeamResponseObject, error)
	// Get a list of projects
	// (GET /teams/{teamName}/projects)
	GetProjects(ctx context.Context, request GetProjectsRequestObject) (GetProjectsResponseObject, error)
	// Create a new project
	// (POST /teams/{teamName}/projects)
	CreateProject(ctx context.Context, request CreateProjectRequestObject) (CreateProjectResponseObject, error)
	// Delete a project
	// (DELETE /teams/{teamName}/projects/{projectName})
	DeleteProject(ctx context.Context, request DeleteProjectRequestObject) (DeleteProjectResponseObject, error)
	// Get a project
	// (GET /teams/{teamName}/projects/{projectName})
	GetProject(ctx context.Context, request GetProjectRequestObject) (GetProjectResponseObject, error)
	// Update a project
	// (PUT /teams/{teamName}/projects/{projectName})
	UpdateProject(ctx context.Context, request UpdateProjectRequestObject) (UpdateProjectResponseObject, error)
	// Get a list of environments
	// (GET /teams/{teamName}/projects/{projectName}/environments)
	GetEnvironments(ctx context.Context, request GetEnvironmentsRequestObject) (GetEnvironmentsResponseObject, error)
	// Create a new environment
	// (POST /teams/{teamName}/projects/{projectName}/environments)
	CreateEnvironment(ctx context.Context, request CreateEnvironmentRequestObject) (CreateEnvironmentResponseObject, error)
	// Delete an environment
	// (DELETE /teams/{teamName}/projects/{projectName}/environments/{environmentName})
	DeleteEnvironment(ctx context.Context, request DeleteEnvironmentRequestObject) (DeleteEnvironmentResponseObject, error)
	// Get an environment
	// (GET /teams/{teamName}/projects/{projectName}/environments/{environmentName})
	GetEnvironment(ctx context.Context, request GetEnvironmentRequestObject) (GetEnvironmentResponseObject, error)
	// Update an environment
	// (PUT /teams/{teamName}/projects/{projectName}/environments/{environmentName})
	UpdateEnvironment(ctx context.Context, request UpdateEnvironmentRequestObject) (UpdateEnvironmentResponseObject, error)
	// Get a list of snapshots
	// (GET /teams/{teamName}/projects/{projectName}/environments/{environmentName}/snapshots)
	GetSnapshots(ctx context.Context, request GetSnapshotsRequestObject) (GetSnapshotsResponseObject, error)
	// Create a new snapshot
	// (POST /teams/{teamName}/projects/{projectName}/environments/{environmentName}/snapshots)
	CreateSnapshot(ctx context.Context, request CreateSnapshotRequestObject) (CreateSnapshotResponseObject, error)
	// Delete a snapshot
	// (DELETE /teams/{teamName}/projects/{projectName}/environments/{environmentName}/snapshots/{snapshotId})
	DeleteSnapshot(ctx context.Context, request DeleteSnapshotRequestObject) (DeleteSnapshotResponseObject, error)
	// Get a snapshot
	// (GET /teams/{teamName}/projects/{projectName}/environments/{environmentName}/snapshots/{snapshotId})
	GetSnapshot(ctx context.Context, request GetSnapshotRequestObject) (GetSnapshotResponseObject, error)
	// Get the state of Terraform environment
	// (GET /teams/{teamName}/projects/{projectName}/environments/{environmentName}/states)
	GetStates(ctx context.Context, request GetStatesRequestObject) (GetStatesResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx *fiber.Ctx) error {
	var request GetHealthRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx.UserContext(), request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetReady operation middleware
func (sh *strictHandler) GetReady(ctx *fiber.Ctx) error {
	var request GetReadyRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetReady(ctx.UserContext(), request.(GetReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReady")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetReadyResponseObject); ok {
		if err := validResponse.VisitGetReadyResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// LockEnvironment operation middleware
func (sh *strictHandler) LockEnvironment(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName) error {
	var request LockEnvironmentRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName
	request.EnvironmentName = environmentName

	var body LockEnvironmentJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.LockEnvironment(ctx.UserContext(), request.(LockEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LockEnvironment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(LockEnvironmentResponseObject); ok {
		if err := validResponse.VisitLockEnvironmentResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetEnvironmentState operation middleware
func (sh *strictHandler) GetEnvironmentState(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName) error {
	var request GetEnvironmentStateRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName
	request.EnvironmentName = environmentName

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetEnvironmentState(ctx.UserContext(), request.(GetEnvironmentStateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEnvironmentState")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetEnvironmentStateResponseObject); ok {
		if err := validResponse.VisitGetEnvironmentStateResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateEnvironmentState operation middleware
func (sh *strictHandler) UpdateEnvironmentState(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName) error {
	var request UpdateEnvironmentStateRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName
	request.EnvironmentName = environmentName

	var body UpdateEnvironmentStateJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateEnvironmentState(ctx.UserContext(), request.(UpdateEnvironmentStateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateEnvironmentState")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UpdateEnvironmentStateResponseObject); ok {
		if err := validResponse.VisitUpdateEnvironmentStateResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UnlockEnvironment operation middleware
func (sh *strictHandler) UnlockEnvironment(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName) error {
	var request UnlockEnvironmentRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName
	request.EnvironmentName = environmentName

	var body UnlockEnvironmentJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UnlockEnvironment(ctx.UserContext(), request.(UnlockEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnlockEnvironment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UnlockEnvironmentResponseObject); ok {
		if err := validResponse.VisitUnlockEnvironmentResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTeams operation middleware
func (sh *strictHandler) GetTeams(ctx *fiber.Ctx, params GetTeamsParams) error {
	var request GetTeamsRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetTeams(ctx.UserContext(), request.(GetTeamsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTeams")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetTeamsResponseObject); ok {
		if err := validResponse.VisitGetTeamsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateTeam operation middleware
func (sh *strictHandler) CreateTeam(ctx *fiber.Ctx) error {
	var request CreateTeamRequestObject

	var body CreateTeamJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTeam(ctx.UserContext(), request.(CreateTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTeam")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateTeamResponseObject); ok {
		if err := validResponse.VisitCreateTeamResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteTeam operation middleware
func (sh *strictHandler) DeleteTeam(ctx *fiber.Ctx, teamName TeamName) error {
	var request DeleteTeamRequestObject

	request.TeamName = teamName

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTeam(ctx.UserContext(), request.(DeleteTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTeam")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteTeamResponseObject); ok {
		if err := validResponse.VisitDeleteTeamResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTeam operation middleware
func (sh *strictHandler) GetTeam(ctx *fiber.Ctx, teamName TeamName) error {
	var request GetTeamRequestObject

	request.TeamName = teamName

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetTeam(ctx.UserContext(), request.(GetTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTeam")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetTeamResponseObject); ok {
		if err := validResponse.VisitGetTeamResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateTeam operation middleware
func (sh *strictHandler) UpdateTeam(ctx *fiber.Ctx, teamName TeamName) error {
	var request UpdateTeamRequestObject

	request.TeamName = teamName

	var body UpdateTeamJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTeam(ctx.UserContext(), request.(UpdateTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTeam")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UpdateTeamResponseObject); ok {
		if err := validResponse.VisitUpdateTeamResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetProjects operation middleware
func (sh *strictHandler) GetProjects(ctx *fiber.Ctx, teamName TeamName, params GetProjectsParams) error {
	var request GetProjectsRequestObject

	request.TeamName = teamName
	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetProjects(ctx.UserContext(), request.(GetProjectsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProjects")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetProjectsResponseObject); ok {
		if err := validResponse.VisitGetProjectsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateProject operation middleware
func (sh *strictHandler) CreateProject(ctx *fiber.Ctx, teamName TeamName) error {
	var request CreateProjectRequestObject

	request.TeamName = teamName

	var body CreateProjectJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProject(ctx.UserContext(), request.(CreateProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateProjectResponseObject); ok {
		if err := validResponse.VisitCreateProjectResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteProject operation middleware
func (sh *strictHandler) DeleteProject(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName) error {
	var request DeleteProjectRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProject(ctx.UserContext(), request.(DeleteProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteProjectResponseObject); ok {
		if err := validResponse.VisitDeleteProjectResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetProject operation middleware
func (sh *strictHandler) GetProject(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName) error {
	var request GetProjectRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetProject(ctx.UserContext(), request.(GetProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetProjectResponseObject); ok {
		if err := validResponse.VisitGetProjectResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateProject operation middleware
func (sh *strictHandler) UpdateProject(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName) error {
	var request UpdateProjectRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName

	var body UpdateProjectJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProject(ctx.UserContext(), request.(UpdateProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UpdateProjectResponseObject); ok {
		if err := validResponse.VisitUpdateProjectResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetEnvironments operation middleware
func (sh *strictHandler) GetEnvironments(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName, params GetEnvironmentsParams) error {
	var request GetEnvironmentsRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName
	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetEnvironments(ctx.UserContext(), request.(GetEnvironmentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEnvironments")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetEnvironmentsResponseObject); ok {
		if err := validResponse.VisitGetEnvironmentsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateEnvironment operation middleware
func (sh *strictHandler) CreateEnvironment(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName) error {
	var request CreateEnvironmentRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName

	var body CreateEnvironmentJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEnvironment(ctx.UserContext(), request.(CreateEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEnvironment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateEnvironmentResponseObject); ok {
		if err := validResponse.VisitCreateEnvironmentResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteEnvironment operation middleware
func (sh *strictHandler) DeleteEnvironment(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName) error {
	var request DeleteEnvironmentRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName
	request.EnvironmentName = environmentName

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteEnvironment(ctx.UserContext(), request.(DeleteEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteEnvironment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteEnvironmentResponseObject); ok {
		if err := validResponse.VisitDeleteEnvironmentResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetEnvironment operation middleware
func (sh *strictHandler) GetEnvironment(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName) error {
	var request GetEnvironmentRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName
	request.EnvironmentName = environmentName

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetEnvironment(ctx.UserContext(), request.(GetEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEnvironment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetEnvironmentResponseObject); ok {
		if err := validResponse.VisitGetEnvironmentResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateEnvironment operation middleware
func (sh *strictHandler) UpdateEnvironment(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName) error {
	var request UpdateEnvironmentRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName
	request.EnvironmentName = environmentName

	var body UpdateEnvironmentJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateEnvironment(ctx.UserContext(), request.(UpdateEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateEnvironment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UpdateEnvironmentResponseObject); ok {
		if err := validResponse.VisitUpdateEnvironmentResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetSnapshots operation middleware
func (sh *strictHandler) GetSnapshots(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName, params GetSnapshotsParams) error {
	var request GetSnapshotsRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName
	request.EnvironmentName = environmentName
	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetSnapshots(ctx.UserContext(), request.(GetSnapshotsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSnapshots")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetSnapshotsResponseObject); ok {
		if err := validResponse.VisitGetSnapshotsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateSnapshot operation middleware
func (sh *strictHandler) CreateSnapshot(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName) error {
	var request CreateSnapshotRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName
	request.EnvironmentName = environmentName

	var body CreateSnapshotJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSnapshot(ctx.UserContext(), request.(CreateSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSnapshot")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateSnapshotResponseObject); ok {
		if err := validResponse.VisitCreateSnapshotResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteSnapshot operation middleware
func (sh *strictHandler) DeleteSnapshot(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName, snapshotId SnapshotId) error {
	var request DeleteSnapshotRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName
	request.EnvironmentName = environmentName
	request.SnapshotId = snapshotId

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSnapshot(ctx.UserContext(), request.(DeleteSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSnapshot")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteSnapshotResponseObject); ok {
		if err := validResponse.VisitDeleteSnapshotResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetSnapshot operation middleware
func (sh *strictHandler) GetSnapshot(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName, snapshotId SnapshotId) error {
	var request GetSnapshotRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName
	request.EnvironmentName = environmentName
	request.SnapshotId = snapshotId

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetSnapshot(ctx.UserContext(), request.(GetSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSnapshot")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetSnapshotResponseObject); ok {
		if err := validResponse.VisitGetSnapshotResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetStates operation middleware
func (sh *strictHandler) GetStates(ctx *fiber.Ctx, teamName TeamName, projectName ProjectName, environmentName EnvironmentName, params GetStatesParams) error {
	var request GetStatesRequestObject

	request.TeamName = teamName
	request.ProjectName = projectName
	request.EnvironmentName = environmentName
	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetStates(ctx.UserContext(), request.(GetStatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStates")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetStatesResponseObject); ok {
		if err := validResponse.VisitGetStatesResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
