// Package apis provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package apis

import (
	"context"
	"fmt"
	"net/url"

	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get system health status
	// (GET /_health)
	GetHealth(c *fiber.Ctx) error
	// Get system readiness
	// (GET /_ready)
	GetReady(c *fiber.Ctx) error
	// Lock the state of Terraform environment
	// (POST /client/{teamId}/{projectId}/{environmentId}/lock)
	LockEnvironment(c *fiber.Ctx, teamId TeamId, projectId ProjectId, environmentId EnvironmentId) error
	// Get the state of Terraform environment
	// (GET /client/{teamId}/{projectId}/{environmentId}/state)
	GetEnvironmentState(c *fiber.Ctx, teamId TeamId, projectId ProjectId, environmentId EnvironmentId) error
	// Update the state of Terraform environment
	// (POST /client/{teamId}/{projectId}/{environmentId}/state)
	UpdateEnvironmentState(c *fiber.Ctx, teamId TeamId, projectId ProjectId, environmentId EnvironmentId, params UpdateEnvironmentStateParams) error
	// Unlock the state of Terraform environment
	// (POST /client/{teamId}/{projectId}/{environmentId}/unlock)
	UnlockEnvironment(c *fiber.Ctx, teamId TeamId, projectId ProjectId, environmentId EnvironmentId) error
	// Get a list of projects
	// (GET /project)
	GetProjects(c *fiber.Ctx, params GetProjectsParams) error
	// Create a new project
	// (POST /project)
	PostProject(c *fiber.Ctx) error
	// Delete a project
	// (DELETE /project/{id})
	DeleteProject(c *fiber.Ctx, id string) error
	// Get a project
	// (GET /project/{id})
	GetProject(c *fiber.Ctx, id string) error
	// Update a project
	// (PUT /project/{id})
	UpdateProject(c *fiber.Ctx, id string) error
	// Get a list of environments
	// (GET /project/{projectId}/environment)
	GetEnvironments(c *fiber.Ctx, projectId string, params GetEnvironmentsParams) error
	// Create a new environment
	// (POST /project/{projectId}/environment)
	PostProjectProjectIdEnvironment(c *fiber.Ctx, projectId string) error
	// Delete an environment
	// (DELETE /project/{projectId}/environment/{environmentId})
	DeleteEnvironment(c *fiber.Ctx, projectId string, environmentId string) error
	// Get an environment
	// (GET /project/{projectId}/environment/{environmentId})
	GetEnvironment(c *fiber.Ctx, projectId string, environmentId string) error
	// Update an environment
	// (PUT /project/{projectId}/environment/{environmentId})
	UpdateEnvironment(c *fiber.Ctx, projectId string, environmentId string) error
	// Get a list of snapshots
	// (GET /snapshot)
	GetSnapshots(c *fiber.Ctx, params GetSnapshotsParams) error
	// Create a new snapshot
	// (POST /snapshot)
	CreateSnapshot(c *fiber.Ctx) error
	// Delete a snapshot
	// (DELETE /snapshot/{id})
	DeleteSnapshot(c *fiber.Ctx, id string) error
	// Get a snapshot
	// (GET /snapshot/{id})
	GetSnapshot(c *fiber.Ctx, id string) error
	// Update a snapshot
	// (PUT /snapshot/{id})
	UpdateSnapshot(c *fiber.Ctx, id string) error
	// Get a task
	// (GET /task/{id})
	GetTask(c *fiber.Ctx, id string) error
	// Get a list of teams
	// (GET /team)
	GetTeams(c *fiber.Ctx, params GetTeamsParams) error
	// Create a new team
	// (POST /team)
	PostTeam(c *fiber.Ctx) error
	// Delete a team
	// (DELETE /team/{id})
	DeleteTeamId(c *fiber.Ctx, id string) error
	// Get a team
	// (GET /team/{id})
	GetTeam(c *fiber.Ctx, id string) error
	// Update a team
	// (PUT /team/{id})
	PutTeamId(c *fiber.Ctx, id string) error
	// Get a list of users
	// (GET /user)
	GetUsers(c *fiber.Ctx, params GetUsersParams) error
	// Create a new user
	// (POST /user)
	PostUser(c *fiber.Ctx) error
	// Delete a user
	// (DELETE /user/{id})
	DeleteUser(c *fiber.Ctx, id string) error
	// Get a user
	// (GET /user/{id})
	GetUser(c *fiber.Ctx, id string) error
	// Update a user
	// (PUT /user/{id})
	UpdateUser(c *fiber.Ctx, id string) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *fiber.Ctx) error {

	return siw.Handler.GetHealth(c)
}

// GetReady operation middleware
func (siw *ServerInterfaceWrapper) GetReady(c *fiber.Ctx) error {

	return siw.Handler.GetReady(c)
}

// LockEnvironment operation middleware
func (siw *ServerInterfaceWrapper) LockEnvironment(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId TeamId

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Params("teamId"), &teamId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamId: %w", err).Error())
	}

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Params("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectId: %w", err).Error())
	}

	// ------------- Path parameter "environmentId" -------------
	var environmentId EnvironmentId

	err = runtime.BindStyledParameterWithOptions("simple", "environmentId", c.Params("environmentId"), &environmentId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentId: %w", err).Error())
	}

	c.Context().SetUserValue(Basic_authScopes, []string{})

	return siw.Handler.LockEnvironment(c, teamId, projectId, environmentId)
}

// GetEnvironmentState operation middleware
func (siw *ServerInterfaceWrapper) GetEnvironmentState(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId TeamId

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Params("teamId"), &teamId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamId: %w", err).Error())
	}

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Params("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectId: %w", err).Error())
	}

	// ------------- Path parameter "environmentId" -------------
	var environmentId EnvironmentId

	err = runtime.BindStyledParameterWithOptions("simple", "environmentId", c.Params("environmentId"), &environmentId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentId: %w", err).Error())
	}

	c.Context().SetUserValue(Basic_authScopes, []string{})

	return siw.Handler.GetEnvironmentState(c, teamId, projectId, environmentId)
}

// UpdateEnvironmentState operation middleware
func (siw *ServerInterfaceWrapper) UpdateEnvironmentState(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId TeamId

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Params("teamId"), &teamId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamId: %w", err).Error())
	}

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Params("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectId: %w", err).Error())
	}

	// ------------- Path parameter "environmentId" -------------
	var environmentId EnvironmentId

	err = runtime.BindStyledParameterWithOptions("simple", "environmentId", c.Params("environmentId"), &environmentId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentId: %w", err).Error())
	}

	c.Context().SetUserValue(Basic_authScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateEnvironmentStateParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "ID" -------------

	err = runtime.BindQueryParameter("form", true, false, "ID", query, &params.ID)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter ID: %w", err).Error())
	}

	return siw.Handler.UpdateEnvironmentState(c, teamId, projectId, environmentId, params)
}

// UnlockEnvironment operation middleware
func (siw *ServerInterfaceWrapper) UnlockEnvironment(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId TeamId

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Params("teamId"), &teamId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter teamId: %w", err).Error())
	}

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Params("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectId: %w", err).Error())
	}

	// ------------- Path parameter "environmentId" -------------
	var environmentId EnvironmentId

	err = runtime.BindStyledParameterWithOptions("simple", "environmentId", c.Params("environmentId"), &environmentId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentId: %w", err).Error())
	}

	c.Context().SetUserValue(Basic_authScopes, []string{})

	return siw.Handler.UnlockEnvironment(c, teamId, projectId, environmentId)
}

// GetProjects operation middleware
func (siw *ServerInterfaceWrapper) GetProjects(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(Api_keyScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProjectsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetProjects(c, params)
}

// PostProject operation middleware
func (siw *ServerInterfaceWrapper) PostProject(c *fiber.Ctx) error {

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.PostProject(c)
}

// DeleteProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteProject(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.DeleteProject(c, id)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.GetProject(c, id)
}

// UpdateProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateProject(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.UpdateProject(c, id)
}

// GetEnvironments operation middleware
func (siw *ServerInterfaceWrapper) GetEnvironments(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Params("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectId: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEnvironmentsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetEnvironments(c, projectId, params)
}

// PostProjectProjectIdEnvironment operation middleware
func (siw *ServerInterfaceWrapper) PostProjectProjectIdEnvironment(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Params("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectId: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.PostProjectProjectIdEnvironment(c, projectId)
}

// DeleteEnvironment operation middleware
func (siw *ServerInterfaceWrapper) DeleteEnvironment(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Params("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectId: %w", err).Error())
	}

	// ------------- Path parameter "environmentId" -------------
	var environmentId string

	err = runtime.BindStyledParameterWithOptions("simple", "environmentId", c.Params("environmentId"), &environmentId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentId: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.DeleteEnvironment(c, projectId, environmentId)
}

// GetEnvironment operation middleware
func (siw *ServerInterfaceWrapper) GetEnvironment(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Params("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectId: %w", err).Error())
	}

	// ------------- Path parameter "environmentId" -------------
	var environmentId string

	err = runtime.BindStyledParameterWithOptions("simple", "environmentId", c.Params("environmentId"), &environmentId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentId: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.GetEnvironment(c, projectId, environmentId)
}

// UpdateEnvironment operation middleware
func (siw *ServerInterfaceWrapper) UpdateEnvironment(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Params("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectId: %w", err).Error())
	}

	// ------------- Path parameter "environmentId" -------------
	var environmentId string

	err = runtime.BindStyledParameterWithOptions("simple", "environmentId", c.Params("environmentId"), &environmentId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter environmentId: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.UpdateEnvironment(c, projectId, environmentId)
}

// GetSnapshots operation middleware
func (siw *ServerInterfaceWrapper) GetSnapshots(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(Api_keyScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSnapshotsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetSnapshots(c, params)
}

// CreateSnapshot operation middleware
func (siw *ServerInterfaceWrapper) CreateSnapshot(c *fiber.Ctx) error {

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.CreateSnapshot(c)
}

// DeleteSnapshot operation middleware
func (siw *ServerInterfaceWrapper) DeleteSnapshot(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.DeleteSnapshot(c, id)
}

// GetSnapshot operation middleware
func (siw *ServerInterfaceWrapper) GetSnapshot(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.GetSnapshot(c, id)
}

// UpdateSnapshot operation middleware
func (siw *ServerInterfaceWrapper) UpdateSnapshot(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.UpdateSnapshot(c, id)
}

// GetTask operation middleware
func (siw *ServerInterfaceWrapper) GetTask(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.GetTask(c, id)
}

// GetTeams operation middleware
func (siw *ServerInterfaceWrapper) GetTeams(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(Api_keyScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetTeams(c, params)
}

// PostTeam operation middleware
func (siw *ServerInterfaceWrapper) PostTeam(c *fiber.Ctx) error {

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.PostTeam(c)
}

// DeleteTeamId operation middleware
func (siw *ServerInterfaceWrapper) DeleteTeamId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.DeleteTeamId(c, id)
}

// GetTeam operation middleware
func (siw *ServerInterfaceWrapper) GetTeam(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.GetTeam(c, id)
}

// PutTeamId operation middleware
func (siw *ServerInterfaceWrapper) PutTeamId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.PutTeamId(c, id)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(Api_keyScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetUsers(c, params)
}

// PostUser operation middleware
func (siw *ServerInterfaceWrapper) PostUser(c *fiber.Ctx) error {

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.PostUser(c)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.DeleteUser(c, id)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.GetUser(c, id)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(Api_keyScopes, []string{})

	return siw.Handler.UpdateUser(c, id)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/_health", wrapper.GetHealth)

	router.Get(options.BaseURL+"/_ready", wrapper.GetReady)

	router.Post(options.BaseURL+"/client/:teamId/:projectId/:environmentId/lock", wrapper.LockEnvironment)

	router.Get(options.BaseURL+"/client/:teamId/:projectId/:environmentId/state", wrapper.GetEnvironmentState)

	router.Post(options.BaseURL+"/client/:teamId/:projectId/:environmentId/state", wrapper.UpdateEnvironmentState)

	router.Post(options.BaseURL+"/client/:teamId/:projectId/:environmentId/unlock", wrapper.UnlockEnvironment)

	router.Get(options.BaseURL+"/project", wrapper.GetProjects)

	router.Post(options.BaseURL+"/project", wrapper.PostProject)

	router.Delete(options.BaseURL+"/project/:id", wrapper.DeleteProject)

	router.Get(options.BaseURL+"/project/:id", wrapper.GetProject)

	router.Put(options.BaseURL+"/project/:id", wrapper.UpdateProject)

	router.Get(options.BaseURL+"/project/:projectId/environment", wrapper.GetEnvironments)

	router.Post(options.BaseURL+"/project/:projectId/environment", wrapper.PostProjectProjectIdEnvironment)

	router.Delete(options.BaseURL+"/project/:projectId/environment/:environmentId", wrapper.DeleteEnvironment)

	router.Get(options.BaseURL+"/project/:projectId/environment/:environmentId", wrapper.GetEnvironment)

	router.Put(options.BaseURL+"/project/:projectId/environment/:environmentId", wrapper.UpdateEnvironment)

	router.Get(options.BaseURL+"/snapshot", wrapper.GetSnapshots)

	router.Post(options.BaseURL+"/snapshot", wrapper.CreateSnapshot)

	router.Delete(options.BaseURL+"/snapshot/:id", wrapper.DeleteSnapshot)

	router.Get(options.BaseURL+"/snapshot/:id", wrapper.GetSnapshot)

	router.Put(options.BaseURL+"/snapshot/:id", wrapper.UpdateSnapshot)

	router.Get(options.BaseURL+"/task/:id", wrapper.GetTask)

	router.Get(options.BaseURL+"/team", wrapper.GetTeams)

	router.Post(options.BaseURL+"/team", wrapper.PostTeam)

	router.Delete(options.BaseURL+"/team/:id", wrapper.DeleteTeamId)

	router.Get(options.BaseURL+"/team/:id", wrapper.GetTeam)

	router.Put(options.BaseURL+"/team/:id", wrapper.PutTeamId)

	router.Get(options.BaseURL+"/user", wrapper.GetUsers)

	router.Post(options.BaseURL+"/user", wrapper.PostUser)

	router.Delete(options.BaseURL+"/user/:id", wrapper.DeleteUser)

	router.Get(options.BaseURL+"/user/:id", wrapper.GetUser)

	router.Put(options.BaseURL+"/user/:id", wrapper.UpdateUser)

}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(ctx *fiber.Ctx) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetHealth500JSONResponse HealthResponse

func (response GetHealth500JSONResponse) VisitGetHealthResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetReadyRequestObject struct {
}

type GetReadyResponseObject interface {
	VisitGetReadyResponse(ctx *fiber.Ctx) error
}

type GetReady200JSONResponse HealthResponse

func (response GetReady200JSONResponse) VisitGetReadyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetReady500JSONResponse HealthResponse

func (response GetReady500JSONResponse) VisitGetReadyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type LockEnvironmentRequestObject struct {
	TeamId        TeamId        `json:"teamId"`
	ProjectId     ProjectId     `json:"projectId"`
	EnvironmentId EnvironmentId `json:"environmentId"`
	Body          *LockEnvironmentJSONRequestBody
}

type LockEnvironmentResponseObject interface {
	VisitLockEnvironmentResponse(ctx *fiber.Ctx) error
}

type LockEnvironment200JSONResponse LockInfo

func (response LockEnvironment200JSONResponse) VisitLockEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type LockEnvironment404JSONResponse ErrorResponse

func (response LockEnvironment404JSONResponse) VisitLockEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type LockEnvironment500JSONResponse ErrorResponse

func (response LockEnvironment500JSONResponse) VisitLockEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetEnvironmentStateRequestObject struct {
	TeamId        TeamId        `json:"teamId"`
	ProjectId     ProjectId     `json:"projectId"`
	EnvironmentId EnvironmentId `json:"environmentId"`
}

type GetEnvironmentStateResponseObject interface {
	VisitGetEnvironmentStateResponse(ctx *fiber.Ctx) error
}

type GetEnvironmentState200JSONResponse Payload

func (response GetEnvironmentState200JSONResponse) VisitGetEnvironmentStateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetEnvironmentState404JSONResponse ErrorResponse

func (response GetEnvironmentState404JSONResponse) VisitGetEnvironmentStateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetEnvironmentState500JSONResponse ErrorResponse

func (response GetEnvironmentState500JSONResponse) VisitGetEnvironmentStateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type UpdateEnvironmentStateRequestObject struct {
	TeamId        TeamId        `json:"teamId"`
	ProjectId     ProjectId     `json:"projectId"`
	EnvironmentId EnvironmentId `json:"environmentId"`
	Params        UpdateEnvironmentStateParams
	Body          *UpdateEnvironmentStateJSONRequestBody
}

type UpdateEnvironmentStateResponseObject interface {
	VisitUpdateEnvironmentStateResponse(ctx *fiber.Ctx) error
}

type UpdateEnvironmentState200JSONResponse Payload

func (response UpdateEnvironmentState200JSONResponse) VisitUpdateEnvironmentStateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type UpdateEnvironmentState404JSONResponse ErrorResponse

func (response UpdateEnvironmentState404JSONResponse) VisitUpdateEnvironmentStateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type UpdateEnvironmentState500JSONResponse ErrorResponse

func (response UpdateEnvironmentState500JSONResponse) VisitUpdateEnvironmentStateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type UnlockEnvironmentRequestObject struct {
	TeamId        TeamId        `json:"teamId"`
	ProjectId     ProjectId     `json:"projectId"`
	EnvironmentId EnvironmentId `json:"environmentId"`
	Body          *UnlockEnvironmentJSONRequestBody
}

type UnlockEnvironmentResponseObject interface {
	VisitUnlockEnvironmentResponse(ctx *fiber.Ctx) error
}

type UnlockEnvironment200Response struct {
}

func (response UnlockEnvironment200Response) VisitUnlockEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type UnlockEnvironment204Response struct {
}

func (response UnlockEnvironment204Response) VisitUnlockEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type UnlockEnvironment404JSONResponse ErrorResponse

func (response UnlockEnvironment404JSONResponse) VisitUnlockEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type UnlockEnvironment500JSONResponse ErrorResponse

func (response UnlockEnvironment500JSONResponse) VisitUnlockEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetProjectsRequestObject struct {
	Params GetProjectsParams
}

type GetProjectsResponseObject interface {
	VisitGetProjectsResponse(ctx *fiber.Ctx) error
}

type GetProjects200JSONResponse struct {
	Metadata *struct {
		Limit      *int `json:"limit,omitempty"`
		Offset     *int `json:"offset,omitempty"`
		TotalCount *int `json:"totalCount,omitempty"`
	} `json:"metadata,omitempty"`
	Projects *[]Project `json:"projects,omitempty"`
}

func (response GetProjects200JSONResponse) VisitGetProjectsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetProjects500JSONResponse ErrorResponse

func (response GetProjects500JSONResponse) VisitGetProjectsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type PostProjectRequestObject struct {
	Body *PostProjectJSONRequestBody
}

type PostProjectResponseObject interface {
	VisitPostProjectResponse(ctx *fiber.Ctx) error
}

type PostProject201JSONResponse Project

func (response PostProject201JSONResponse) VisitPostProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type PostProject500JSONResponse ErrorResponse

func (response PostProject500JSONResponse) VisitPostProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type DeleteProjectRequestObject struct {
	Id string `json:"id"`
}

type DeleteProjectResponseObject interface {
	VisitDeleteProjectResponse(ctx *fiber.Ctx) error
}

type DeleteProject204Response struct {
}

func (response DeleteProject204Response) VisitDeleteProjectResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type DeleteProject404JSONResponse ErrorResponse

func (response DeleteProject404JSONResponse) VisitDeleteProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type DeleteProject500JSONResponse ErrorResponse

func (response DeleteProject500JSONResponse) VisitDeleteProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetProjectRequestObject struct {
	Id string `json:"id"`
}

type GetProjectResponseObject interface {
	VisitGetProjectResponse(ctx *fiber.Ctx) error
}

type GetProject200JSONResponse Project

func (response GetProject200JSONResponse) VisitGetProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetProject404JSONResponse ErrorResponse

func (response GetProject404JSONResponse) VisitGetProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetProject500JSONResponse ErrorResponse

func (response GetProject500JSONResponse) VisitGetProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type UpdateProjectRequestObject struct {
	Id   string `json:"id"`
	Body *UpdateProjectJSONRequestBody
}

type UpdateProjectResponseObject interface {
	VisitUpdateProjectResponse(ctx *fiber.Ctx) error
}

type UpdateProject200JSONResponse Project

func (response UpdateProject200JSONResponse) VisitUpdateProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type UpdateProject404JSONResponse ErrorResponse

func (response UpdateProject404JSONResponse) VisitUpdateProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type UpdateProject500JSONResponse ErrorResponse

func (response UpdateProject500JSONResponse) VisitUpdateProjectResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetEnvironmentsRequestObject struct {
	ProjectId string `json:"projectId"`
	Params    GetEnvironmentsParams
}

type GetEnvironmentsResponseObject interface {
	VisitGetEnvironmentsResponse(ctx *fiber.Ctx) error
}

type GetEnvironments200JSONResponse struct {
	Environments *[]Environment `json:"environments,omitempty"`
	Metadata     *struct {
		Limit      *int `json:"limit,omitempty"`
		Offset     *int `json:"offset,omitempty"`
		TotalCount *int `json:"totalCount,omitempty"`
	} `json:"metadata,omitempty"`
}

func (response GetEnvironments200JSONResponse) VisitGetEnvironmentsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetEnvironments500JSONResponse ErrorResponse

func (response GetEnvironments500JSONResponse) VisitGetEnvironmentsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type PostProjectProjectIdEnvironmentRequestObject struct {
	ProjectId string `json:"projectId"`
	Body      *PostProjectProjectIdEnvironmentJSONRequestBody
}

type PostProjectProjectIdEnvironmentResponseObject interface {
	VisitPostProjectProjectIdEnvironmentResponse(ctx *fiber.Ctx) error
}

type PostProjectProjectIdEnvironment201JSONResponse Environment

func (response PostProjectProjectIdEnvironment201JSONResponse) VisitPostProjectProjectIdEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type PostProjectProjectIdEnvironment500JSONResponse ErrorResponse

func (response PostProjectProjectIdEnvironment500JSONResponse) VisitPostProjectProjectIdEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type DeleteEnvironmentRequestObject struct {
	ProjectId     string `json:"projectId"`
	EnvironmentId string `json:"environmentId"`
}

type DeleteEnvironmentResponseObject interface {
	VisitDeleteEnvironmentResponse(ctx *fiber.Ctx) error
}

type DeleteEnvironment204Response struct {
}

func (response DeleteEnvironment204Response) VisitDeleteEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type DeleteEnvironment404JSONResponse ErrorResponse

func (response DeleteEnvironment404JSONResponse) VisitDeleteEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type DeleteEnvironment500JSONResponse ErrorResponse

func (response DeleteEnvironment500JSONResponse) VisitDeleteEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetEnvironmentRequestObject struct {
	ProjectId     string `json:"projectId"`
	EnvironmentId string `json:"environmentId"`
}

type GetEnvironmentResponseObject interface {
	VisitGetEnvironmentResponse(ctx *fiber.Ctx) error
}

type GetEnvironment200JSONResponse Environment

func (response GetEnvironment200JSONResponse) VisitGetEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetEnvironment404JSONResponse ErrorResponse

func (response GetEnvironment404JSONResponse) VisitGetEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetEnvironment500JSONResponse ErrorResponse

func (response GetEnvironment500JSONResponse) VisitGetEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type UpdateEnvironmentRequestObject struct {
	ProjectId     string `json:"projectId"`
	EnvironmentId string `json:"environmentId"`
	Body          *UpdateEnvironmentJSONRequestBody
}

type UpdateEnvironmentResponseObject interface {
	VisitUpdateEnvironmentResponse(ctx *fiber.Ctx) error
}

type UpdateEnvironment200JSONResponse Environment

func (response UpdateEnvironment200JSONResponse) VisitUpdateEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type UpdateEnvironment404JSONResponse ErrorResponse

func (response UpdateEnvironment404JSONResponse) VisitUpdateEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type UpdateEnvironment500JSONResponse ErrorResponse

func (response UpdateEnvironment500JSONResponse) VisitUpdateEnvironmentResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetSnapshotsRequestObject struct {
	Params GetSnapshotsParams
}

type GetSnapshotsResponseObject interface {
	VisitGetSnapshotsResponse(ctx *fiber.Ctx) error
}

type GetSnapshots200JSONResponse struct {
	Metadata *struct {
		Limit      *int `json:"limit,omitempty"`
		Offset     *int `json:"offset,omitempty"`
		TotalCount *int `json:"totalCount,omitempty"`
	} `json:"metadata,omitempty"`
	Snapshots *[]Snapshot `json:"snapshots,omitempty"`
}

func (response GetSnapshots200JSONResponse) VisitGetSnapshotsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetSnapshots500JSONResponse ErrorResponse

func (response GetSnapshots500JSONResponse) VisitGetSnapshotsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type CreateSnapshotRequestObject struct {
	Body *CreateSnapshotJSONRequestBody
}

type CreateSnapshotResponseObject interface {
	VisitCreateSnapshotResponse(ctx *fiber.Ctx) error
}

type CreateSnapshot201JSONResponse Snapshot

func (response CreateSnapshot201JSONResponse) VisitCreateSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type CreateSnapshot500JSONResponse ErrorResponse

func (response CreateSnapshot500JSONResponse) VisitCreateSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type DeleteSnapshotRequestObject struct {
	Id string `json:"id"`
}

type DeleteSnapshotResponseObject interface {
	VisitDeleteSnapshotResponse(ctx *fiber.Ctx) error
}

type DeleteSnapshot204Response struct {
}

func (response DeleteSnapshot204Response) VisitDeleteSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type DeleteSnapshot404JSONResponse ErrorResponse

func (response DeleteSnapshot404JSONResponse) VisitDeleteSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type DeleteSnapshot500JSONResponse ErrorResponse

func (response DeleteSnapshot500JSONResponse) VisitDeleteSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetSnapshotRequestObject struct {
	Id string `json:"id"`
}

type GetSnapshotResponseObject interface {
	VisitGetSnapshotResponse(ctx *fiber.Ctx) error
}

type GetSnapshot200JSONResponse Snapshot

func (response GetSnapshot200JSONResponse) VisitGetSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetSnapshot404JSONResponse ErrorResponse

func (response GetSnapshot404JSONResponse) VisitGetSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetSnapshot500JSONResponse ErrorResponse

func (response GetSnapshot500JSONResponse) VisitGetSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type UpdateSnapshotRequestObject struct {
	Id   string `json:"id"`
	Body *UpdateSnapshotJSONRequestBody
}

type UpdateSnapshotResponseObject interface {
	VisitUpdateSnapshotResponse(ctx *fiber.Ctx) error
}

type UpdateSnapshot200JSONResponse Snapshot

func (response UpdateSnapshot200JSONResponse) VisitUpdateSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type UpdateSnapshot404JSONResponse ErrorResponse

func (response UpdateSnapshot404JSONResponse) VisitUpdateSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type UpdateSnapshot500JSONResponse ErrorResponse

func (response UpdateSnapshot500JSONResponse) VisitUpdateSnapshotResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetTaskRequestObject struct {
	Id string `json:"id"`
}

type GetTaskResponseObject interface {
	VisitGetTaskResponse(ctx *fiber.Ctx) error
}

type GetTask200JSONResponse Task

func (response GetTask200JSONResponse) VisitGetTaskResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetTask404JSONResponse ErrorResponse

func (response GetTask404JSONResponse) VisitGetTaskResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetTask500JSONResponse ErrorResponse

func (response GetTask500JSONResponse) VisitGetTaskResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetTeamsRequestObject struct {
	Params GetTeamsParams
}

type GetTeamsResponseObject interface {
	VisitGetTeamsResponse(ctx *fiber.Ctx) error
}

type GetTeams200JSONResponse struct {
	Metadata *struct {
		Limit      *int `json:"limit,omitempty"`
		Offset     *int `json:"offset,omitempty"`
		TotalCount *int `json:"totalCount,omitempty"`
	} `json:"metadata,omitempty"`
	Teams *[]Team `json:"teams,omitempty"`
}

func (response GetTeams200JSONResponse) VisitGetTeamsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetTeams500JSONResponse ErrorResponse

func (response GetTeams500JSONResponse) VisitGetTeamsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type PostTeamRequestObject struct {
	Body *PostTeamJSONRequestBody
}

type PostTeamResponseObject interface {
	VisitPostTeamResponse(ctx *fiber.Ctx) error
}

type PostTeam201JSONResponse Team

func (response PostTeam201JSONResponse) VisitPostTeamResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type PostTeam500JSONResponse ErrorResponse

func (response PostTeam500JSONResponse) VisitPostTeamResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type DeleteTeamIdRequestObject struct {
	Id string `json:"id"`
}

type DeleteTeamIdResponseObject interface {
	VisitDeleteTeamIdResponse(ctx *fiber.Ctx) error
}

type DeleteTeamId204Response struct {
}

func (response DeleteTeamId204Response) VisitDeleteTeamIdResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type DeleteTeamId404JSONResponse ErrorResponse

func (response DeleteTeamId404JSONResponse) VisitDeleteTeamIdResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type DeleteTeamId500JSONResponse ErrorResponse

func (response DeleteTeamId500JSONResponse) VisitDeleteTeamIdResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetTeamRequestObject struct {
	Id string `json:"id"`
}

type GetTeamResponseObject interface {
	VisitGetTeamResponse(ctx *fiber.Ctx) error
}

type GetTeam200JSONResponse Team

func (response GetTeam200JSONResponse) VisitGetTeamResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetTeam404JSONResponse ErrorResponse

func (response GetTeam404JSONResponse) VisitGetTeamResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetTeam500JSONResponse ErrorResponse

func (response GetTeam500JSONResponse) VisitGetTeamResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type PutTeamIdRequestObject struct {
	Id   string `json:"id"`
	Body *PutTeamIdJSONRequestBody
}

type PutTeamIdResponseObject interface {
	VisitPutTeamIdResponse(ctx *fiber.Ctx) error
}

type PutTeamId200JSONResponse Team

func (response PutTeamId200JSONResponse) VisitPutTeamIdResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type PutTeamId404JSONResponse ErrorResponse

func (response PutTeamId404JSONResponse) VisitPutTeamIdResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type PutTeamId500JSONResponse ErrorResponse

func (response PutTeamId500JSONResponse) VisitPutTeamIdResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetUsersRequestObject struct {
	Params GetUsersParams
}

type GetUsersResponseObject interface {
	VisitGetUsersResponse(ctx *fiber.Ctx) error
}

type GetUsers200JSONResponse struct {
	Metadata *struct {
		Limit      *int `json:"limit,omitempty"`
		Offset     *int `json:"offset,omitempty"`
		TotalCount *int `json:"totalCount,omitempty"`
	} `json:"metadata,omitempty"`
	Users *[]User `json:"users,omitempty"`
}

func (response GetUsers200JSONResponse) VisitGetUsersResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetUsers500JSONResponse ErrorResponse

func (response GetUsers500JSONResponse) VisitGetUsersResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type PostUserRequestObject struct {
	Body *PostUserJSONRequestBody
}

type PostUserResponseObject interface {
	VisitPostUserResponse(ctx *fiber.Ctx) error
}

type PostUser201JSONResponse User

func (response PostUser201JSONResponse) VisitPostUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type PostUser500JSONResponse ErrorResponse

func (response PostUser500JSONResponse) VisitPostUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type DeleteUserRequestObject struct {
	Id string `json:"id"`
}

type DeleteUserResponseObject interface {
	VisitDeleteUserResponse(ctx *fiber.Ctx) error
}

type DeleteUser204Response struct {
}

func (response DeleteUser204Response) VisitDeleteUserResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type DeleteUser404JSONResponse ErrorResponse

func (response DeleteUser404JSONResponse) VisitDeleteUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type DeleteUser500JSONResponse ErrorResponse

func (response DeleteUser500JSONResponse) VisitDeleteUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetUserRequestObject struct {
	Id string `json:"id"`
}

type GetUserResponseObject interface {
	VisitGetUserResponse(ctx *fiber.Ctx) error
}

type GetUser200JSONResponse User

func (response GetUser200JSONResponse) VisitGetUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetUser404JSONResponse ErrorResponse

func (response GetUser404JSONResponse) VisitGetUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetUser500JSONResponse ErrorResponse

func (response GetUser500JSONResponse) VisitGetUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type UpdateUserRequestObject struct {
	Id   string `json:"id"`
	Body *UpdateUserJSONRequestBody
}

type UpdateUserResponseObject interface {
	VisitUpdateUserResponse(ctx *fiber.Ctx) error
}

type UpdateUser200JSONResponse User

func (response UpdateUser200JSONResponse) VisitUpdateUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type UpdateUser404JSONResponse ErrorResponse

func (response UpdateUser404JSONResponse) VisitUpdateUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type UpdateUser500JSONResponse ErrorResponse

func (response UpdateUser500JSONResponse) VisitUpdateUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get system health status
	// (GET /_health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Get system readiness
	// (GET /_ready)
	GetReady(ctx context.Context, request GetReadyRequestObject) (GetReadyResponseObject, error)
	// Lock the state of Terraform environment
	// (POST /client/{teamId}/{projectId}/{environmentId}/lock)
	LockEnvironment(ctx context.Context, request LockEnvironmentRequestObject) (LockEnvironmentResponseObject, error)
	// Get the state of Terraform environment
	// (GET /client/{teamId}/{projectId}/{environmentId}/state)
	GetEnvironmentState(ctx context.Context, request GetEnvironmentStateRequestObject) (GetEnvironmentStateResponseObject, error)
	// Update the state of Terraform environment
	// (POST /client/{teamId}/{projectId}/{environmentId}/state)
	UpdateEnvironmentState(ctx context.Context, request UpdateEnvironmentStateRequestObject) (UpdateEnvironmentStateResponseObject, error)
	// Unlock the state of Terraform environment
	// (POST /client/{teamId}/{projectId}/{environmentId}/unlock)
	UnlockEnvironment(ctx context.Context, request UnlockEnvironmentRequestObject) (UnlockEnvironmentResponseObject, error)
	// Get a list of projects
	// (GET /project)
	GetProjects(ctx context.Context, request GetProjectsRequestObject) (GetProjectsResponseObject, error)
	// Create a new project
	// (POST /project)
	PostProject(ctx context.Context, request PostProjectRequestObject) (PostProjectResponseObject, error)
	// Delete a project
	// (DELETE /project/{id})
	DeleteProject(ctx context.Context, request DeleteProjectRequestObject) (DeleteProjectResponseObject, error)
	// Get a project
	// (GET /project/{id})
	GetProject(ctx context.Context, request GetProjectRequestObject) (GetProjectResponseObject, error)
	// Update a project
	// (PUT /project/{id})
	UpdateProject(ctx context.Context, request UpdateProjectRequestObject) (UpdateProjectResponseObject, error)
	// Get a list of environments
	// (GET /project/{projectId}/environment)
	GetEnvironments(ctx context.Context, request GetEnvironmentsRequestObject) (GetEnvironmentsResponseObject, error)
	// Create a new environment
	// (POST /project/{projectId}/environment)
	PostProjectProjectIdEnvironment(ctx context.Context, request PostProjectProjectIdEnvironmentRequestObject) (PostProjectProjectIdEnvironmentResponseObject, error)
	// Delete an environment
	// (DELETE /project/{projectId}/environment/{environmentId})
	DeleteEnvironment(ctx context.Context, request DeleteEnvironmentRequestObject) (DeleteEnvironmentResponseObject, error)
	// Get an environment
	// (GET /project/{projectId}/environment/{environmentId})
	GetEnvironment(ctx context.Context, request GetEnvironmentRequestObject) (GetEnvironmentResponseObject, error)
	// Update an environment
	// (PUT /project/{projectId}/environment/{environmentId})
	UpdateEnvironment(ctx context.Context, request UpdateEnvironmentRequestObject) (UpdateEnvironmentResponseObject, error)
	// Get a list of snapshots
	// (GET /snapshot)
	GetSnapshots(ctx context.Context, request GetSnapshotsRequestObject) (GetSnapshotsResponseObject, error)
	// Create a new snapshot
	// (POST /snapshot)
	CreateSnapshot(ctx context.Context, request CreateSnapshotRequestObject) (CreateSnapshotResponseObject, error)
	// Delete a snapshot
	// (DELETE /snapshot/{id})
	DeleteSnapshot(ctx context.Context, request DeleteSnapshotRequestObject) (DeleteSnapshotResponseObject, error)
	// Get a snapshot
	// (GET /snapshot/{id})
	GetSnapshot(ctx context.Context, request GetSnapshotRequestObject) (GetSnapshotResponseObject, error)
	// Update a snapshot
	// (PUT /snapshot/{id})
	UpdateSnapshot(ctx context.Context, request UpdateSnapshotRequestObject) (UpdateSnapshotResponseObject, error)
	// Get a task
	// (GET /task/{id})
	GetTask(ctx context.Context, request GetTaskRequestObject) (GetTaskResponseObject, error)
	// Get a list of teams
	// (GET /team)
	GetTeams(ctx context.Context, request GetTeamsRequestObject) (GetTeamsResponseObject, error)
	// Create a new team
	// (POST /team)
	PostTeam(ctx context.Context, request PostTeamRequestObject) (PostTeamResponseObject, error)
	// Delete a team
	// (DELETE /team/{id})
	DeleteTeamId(ctx context.Context, request DeleteTeamIdRequestObject) (DeleteTeamIdResponseObject, error)
	// Get a team
	// (GET /team/{id})
	GetTeam(ctx context.Context, request GetTeamRequestObject) (GetTeamResponseObject, error)
	// Update a team
	// (PUT /team/{id})
	PutTeamId(ctx context.Context, request PutTeamIdRequestObject) (PutTeamIdResponseObject, error)
	// Get a list of users
	// (GET /user)
	GetUsers(ctx context.Context, request GetUsersRequestObject) (GetUsersResponseObject, error)
	// Create a new user
	// (POST /user)
	PostUser(ctx context.Context, request PostUserRequestObject) (PostUserResponseObject, error)
	// Delete a user
	// (DELETE /user/{id})
	DeleteUser(ctx context.Context, request DeleteUserRequestObject) (DeleteUserResponseObject, error)
	// Get a user
	// (GET /user/{id})
	GetUser(ctx context.Context, request GetUserRequestObject) (GetUserResponseObject, error)
	// Update a user
	// (PUT /user/{id})
	UpdateUser(ctx context.Context, request UpdateUserRequestObject) (UpdateUserResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx *fiber.Ctx) error {
	var request GetHealthRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx.UserContext(), request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetReady operation middleware
func (sh *strictHandler) GetReady(ctx *fiber.Ctx) error {
	var request GetReadyRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetReady(ctx.UserContext(), request.(GetReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReady")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetReadyResponseObject); ok {
		if err := validResponse.VisitGetReadyResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// LockEnvironment operation middleware
func (sh *strictHandler) LockEnvironment(ctx *fiber.Ctx, teamId TeamId, projectId ProjectId, environmentId EnvironmentId) error {
	var request LockEnvironmentRequestObject

	request.TeamId = teamId
	request.ProjectId = projectId
	request.EnvironmentId = environmentId

	var body LockEnvironmentJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.LockEnvironment(ctx.UserContext(), request.(LockEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LockEnvironment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(LockEnvironmentResponseObject); ok {
		if err := validResponse.VisitLockEnvironmentResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetEnvironmentState operation middleware
func (sh *strictHandler) GetEnvironmentState(ctx *fiber.Ctx, teamId TeamId, projectId ProjectId, environmentId EnvironmentId) error {
	var request GetEnvironmentStateRequestObject

	request.TeamId = teamId
	request.ProjectId = projectId
	request.EnvironmentId = environmentId

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetEnvironmentState(ctx.UserContext(), request.(GetEnvironmentStateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEnvironmentState")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetEnvironmentStateResponseObject); ok {
		if err := validResponse.VisitGetEnvironmentStateResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateEnvironmentState operation middleware
func (sh *strictHandler) UpdateEnvironmentState(ctx *fiber.Ctx, teamId TeamId, projectId ProjectId, environmentId EnvironmentId, params UpdateEnvironmentStateParams) error {
	var request UpdateEnvironmentStateRequestObject

	request.TeamId = teamId
	request.ProjectId = projectId
	request.EnvironmentId = environmentId
	request.Params = params

	var body UpdateEnvironmentStateJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateEnvironmentState(ctx.UserContext(), request.(UpdateEnvironmentStateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateEnvironmentState")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UpdateEnvironmentStateResponseObject); ok {
		if err := validResponse.VisitUpdateEnvironmentStateResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UnlockEnvironment operation middleware
func (sh *strictHandler) UnlockEnvironment(ctx *fiber.Ctx, teamId TeamId, projectId ProjectId, environmentId EnvironmentId) error {
	var request UnlockEnvironmentRequestObject

	request.TeamId = teamId
	request.ProjectId = projectId
	request.EnvironmentId = environmentId

	var body UnlockEnvironmentJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UnlockEnvironment(ctx.UserContext(), request.(UnlockEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnlockEnvironment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UnlockEnvironmentResponseObject); ok {
		if err := validResponse.VisitUnlockEnvironmentResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetProjects operation middleware
func (sh *strictHandler) GetProjects(ctx *fiber.Ctx, params GetProjectsParams) error {
	var request GetProjectsRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetProjects(ctx.UserContext(), request.(GetProjectsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProjects")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetProjectsResponseObject); ok {
		if err := validResponse.VisitGetProjectsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostProject operation middleware
func (sh *strictHandler) PostProject(ctx *fiber.Ctx) error {
	var request PostProjectRequestObject

	var body PostProjectJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.PostProject(ctx.UserContext(), request.(PostProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(PostProjectResponseObject); ok {
		if err := validResponse.VisitPostProjectResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteProject operation middleware
func (sh *strictHandler) DeleteProject(ctx *fiber.Ctx, id string) error {
	var request DeleteProjectRequestObject

	request.Id = id

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProject(ctx.UserContext(), request.(DeleteProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteProjectResponseObject); ok {
		if err := validResponse.VisitDeleteProjectResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetProject operation middleware
func (sh *strictHandler) GetProject(ctx *fiber.Ctx, id string) error {
	var request GetProjectRequestObject

	request.Id = id

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetProject(ctx.UserContext(), request.(GetProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetProjectResponseObject); ok {
		if err := validResponse.VisitGetProjectResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateProject operation middleware
func (sh *strictHandler) UpdateProject(ctx *fiber.Ctx, id string) error {
	var request UpdateProjectRequestObject

	request.Id = id

	var body UpdateProjectJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProject(ctx.UserContext(), request.(UpdateProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UpdateProjectResponseObject); ok {
		if err := validResponse.VisitUpdateProjectResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetEnvironments operation middleware
func (sh *strictHandler) GetEnvironments(ctx *fiber.Ctx, projectId string, params GetEnvironmentsParams) error {
	var request GetEnvironmentsRequestObject

	request.ProjectId = projectId
	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetEnvironments(ctx.UserContext(), request.(GetEnvironmentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEnvironments")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetEnvironmentsResponseObject); ok {
		if err := validResponse.VisitGetEnvironmentsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostProjectProjectIdEnvironment operation middleware
func (sh *strictHandler) PostProjectProjectIdEnvironment(ctx *fiber.Ctx, projectId string) error {
	var request PostProjectProjectIdEnvironmentRequestObject

	request.ProjectId = projectId

	var body PostProjectProjectIdEnvironmentJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.PostProjectProjectIdEnvironment(ctx.UserContext(), request.(PostProjectProjectIdEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostProjectProjectIdEnvironment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(PostProjectProjectIdEnvironmentResponseObject); ok {
		if err := validResponse.VisitPostProjectProjectIdEnvironmentResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteEnvironment operation middleware
func (sh *strictHandler) DeleteEnvironment(ctx *fiber.Ctx, projectId string, environmentId string) error {
	var request DeleteEnvironmentRequestObject

	request.ProjectId = projectId
	request.EnvironmentId = environmentId

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteEnvironment(ctx.UserContext(), request.(DeleteEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteEnvironment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteEnvironmentResponseObject); ok {
		if err := validResponse.VisitDeleteEnvironmentResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetEnvironment operation middleware
func (sh *strictHandler) GetEnvironment(ctx *fiber.Ctx, projectId string, environmentId string) error {
	var request GetEnvironmentRequestObject

	request.ProjectId = projectId
	request.EnvironmentId = environmentId

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetEnvironment(ctx.UserContext(), request.(GetEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEnvironment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetEnvironmentResponseObject); ok {
		if err := validResponse.VisitGetEnvironmentResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateEnvironment operation middleware
func (sh *strictHandler) UpdateEnvironment(ctx *fiber.Ctx, projectId string, environmentId string) error {
	var request UpdateEnvironmentRequestObject

	request.ProjectId = projectId
	request.EnvironmentId = environmentId

	var body UpdateEnvironmentJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateEnvironment(ctx.UserContext(), request.(UpdateEnvironmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateEnvironment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UpdateEnvironmentResponseObject); ok {
		if err := validResponse.VisitUpdateEnvironmentResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetSnapshots operation middleware
func (sh *strictHandler) GetSnapshots(ctx *fiber.Ctx, params GetSnapshotsParams) error {
	var request GetSnapshotsRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetSnapshots(ctx.UserContext(), request.(GetSnapshotsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSnapshots")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetSnapshotsResponseObject); ok {
		if err := validResponse.VisitGetSnapshotsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateSnapshot operation middleware
func (sh *strictHandler) CreateSnapshot(ctx *fiber.Ctx) error {
	var request CreateSnapshotRequestObject

	var body CreateSnapshotJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSnapshot(ctx.UserContext(), request.(CreateSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSnapshot")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateSnapshotResponseObject); ok {
		if err := validResponse.VisitCreateSnapshotResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteSnapshot operation middleware
func (sh *strictHandler) DeleteSnapshot(ctx *fiber.Ctx, id string) error {
	var request DeleteSnapshotRequestObject

	request.Id = id

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSnapshot(ctx.UserContext(), request.(DeleteSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSnapshot")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteSnapshotResponseObject); ok {
		if err := validResponse.VisitDeleteSnapshotResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetSnapshot operation middleware
func (sh *strictHandler) GetSnapshot(ctx *fiber.Ctx, id string) error {
	var request GetSnapshotRequestObject

	request.Id = id

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetSnapshot(ctx.UserContext(), request.(GetSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSnapshot")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetSnapshotResponseObject); ok {
		if err := validResponse.VisitGetSnapshotResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateSnapshot operation middleware
func (sh *strictHandler) UpdateSnapshot(ctx *fiber.Ctx, id string) error {
	var request UpdateSnapshotRequestObject

	request.Id = id

	var body UpdateSnapshotJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSnapshot(ctx.UserContext(), request.(UpdateSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSnapshot")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UpdateSnapshotResponseObject); ok {
		if err := validResponse.VisitUpdateSnapshotResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTask operation middleware
func (sh *strictHandler) GetTask(ctx *fiber.Ctx, id string) error {
	var request GetTaskRequestObject

	request.Id = id

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetTask(ctx.UserContext(), request.(GetTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetTaskResponseObject); ok {
		if err := validResponse.VisitGetTaskResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTeams operation middleware
func (sh *strictHandler) GetTeams(ctx *fiber.Ctx, params GetTeamsParams) error {
	var request GetTeamsRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetTeams(ctx.UserContext(), request.(GetTeamsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTeams")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetTeamsResponseObject); ok {
		if err := validResponse.VisitGetTeamsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostTeam operation middleware
func (sh *strictHandler) PostTeam(ctx *fiber.Ctx) error {
	var request PostTeamRequestObject

	var body PostTeamJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.PostTeam(ctx.UserContext(), request.(PostTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostTeam")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(PostTeamResponseObject); ok {
		if err := validResponse.VisitPostTeamResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteTeamId operation middleware
func (sh *strictHandler) DeleteTeamId(ctx *fiber.Ctx, id string) error {
	var request DeleteTeamIdRequestObject

	request.Id = id

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTeamId(ctx.UserContext(), request.(DeleteTeamIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTeamId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteTeamIdResponseObject); ok {
		if err := validResponse.VisitDeleteTeamIdResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTeam operation middleware
func (sh *strictHandler) GetTeam(ctx *fiber.Ctx, id string) error {
	var request GetTeamRequestObject

	request.Id = id

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetTeam(ctx.UserContext(), request.(GetTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTeam")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetTeamResponseObject); ok {
		if err := validResponse.VisitGetTeamResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PutTeamId operation middleware
func (sh *strictHandler) PutTeamId(ctx *fiber.Ctx, id string) error {
	var request PutTeamIdRequestObject

	request.Id = id

	var body PutTeamIdJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.PutTeamId(ctx.UserContext(), request.(PutTeamIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutTeamId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(PutTeamIdResponseObject); ok {
		if err := validResponse.VisitPutTeamIdResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUsers operation middleware
func (sh *strictHandler) GetUsers(ctx *fiber.Ctx, params GetUsersParams) error {
	var request GetUsersRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsers(ctx.UserContext(), request.(GetUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetUsersResponseObject); ok {
		if err := validResponse.VisitGetUsersResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostUser operation middleware
func (sh *strictHandler) PostUser(ctx *fiber.Ctx) error {
	var request PostUserRequestObject

	var body PostUserJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.PostUser(ctx.UserContext(), request.(PostUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(PostUserResponseObject); ok {
		if err := validResponse.VisitPostUserResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteUser operation middleware
func (sh *strictHandler) DeleteUser(ctx *fiber.Ctx, id string) error {
	var request DeleteUserRequestObject

	request.Id = id

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteUser(ctx.UserContext(), request.(DeleteUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DeleteUserResponseObject); ok {
		if err := validResponse.VisitDeleteUserResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUser operation middleware
func (sh *strictHandler) GetUser(ctx *fiber.Ctx, id string) error {
	var request GetUserRequestObject

	request.Id = id

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetUser(ctx.UserContext(), request.(GetUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetUserResponseObject); ok {
		if err := validResponse.VisitGetUserResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateUser operation middleware
func (sh *strictHandler) UpdateUser(ctx *fiber.Ctx, id string) error {
	var request UpdateUserRequestObject

	request.Id = id

	var body UpdateUserJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUser(ctx.UserContext(), request.(UpdateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(UpdateUserResponseObject); ok {
		if err := validResponse.VisitUpdateUserResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
