# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/main/configuration-schema.json
package: apis
generate:
  client: true
output: ../pkg/apis/client.gen.go
output-options:
  skip-prune: true