# .github/workflows/docs.yml

name: Build docs

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v6
      - run: |
          make docs
      - uses: peaceiris/actions-gh-pages@v4
        with:
          keep_files: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
