# .github/workflows/docs.yml

name: Build docs

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - uses: actions/setup-node@v4
    - run: |
        make docs
    - uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        keep_files: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public