# .github/workflows/docs.yml

name: Build docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - uses: actions/configure-pages@v5
    - uses: actions/setup-node@v4
    - run: |
        make docs
    - uses: actions/upload-pages-artifact@v3
      with:
        path: './public'
    - id: deployment
      uses: actions/deploy-pages@v4