# .github/workflows/release.yml

name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: zeiss/knox
  REGISTRY: ghcr.io

jobs:
  test:
    permissions:
      checks: write
    uses: ./.github/workflows/main.yml

  release:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v5
      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-go@v6
        with:
          go-version-file: ./tools/go.mod
      - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: sudo apt-get update && sudo apt install -y libxml2-dev libxslt1-dev liblzma-dev zlib1g-dev
      - run: |
          make release
      - run: |
          go run internal/tools/updater/main.go --file helm/charts/knox/Chart.yaml --version ${{ env.RELEASE_VERSION }}
      - uses: azure/setup-helm@v4
        with:
          version: v3.11.2
      - uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: helm/charts
          config: helm/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/upload-artifact@v4
        with:
          name: manifests
          path: /tmp/dist
          retention-days: 14
